# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# Ref: https://github.com/Homebrew/brew/blob/master/Library/Homebrew/dev-cmd/tap-new.rb

strategy:
  matrix:
    mojave:
      imageName: 'macOS-10.14'
      xcodeVersion: '10.2'
    high_sierra:
      imageName: 'macOS-10.13'
      xcodeVersion: '10.1'

pool:
  vmImage: $(imageName)

steps:
- bash: |
    set -e
    sudo xcode-select --switch /Applications/Xcode_$(xcodeVersion).app/Contents/Developer
    brew update
    HOMEBREW_TAP_DIR="$(brew --repo)"/Library/Taps/"$BUILD_REPOSITORY_ID"
    mkdir -p $(dirname "$HOMEBREW_TAP_DIR")
    rm -rf "$HOMEBREW_TAP_DIR"
    ln -s "$PWD" "$HOMEBREW_TAP_DIR"
    brew cask install xquartz
    brew test-bot
  displayName: Run brew test-bot
  env:
    HOMEBREW_NO_ANALYTICS: 1
    HOMEBREW_NO_AUTO_UPDATE: 1
